### ISSUE TITLE
shader_set_ext sampler addition

### ISSUE THREAD

**Issue by Gizmo199** [DAndrewBox/GML-Extended#1]
I have a script I use that is very similar to your shader_set_ext() function, but my version has checks for pointers so that you can automatically set `surface/sprite_get_texture()` as a parameter and it will automatically run `texture_set_stage()` if the value is a pointer. 

Link: https://pastebin.com/xrXzxjBw

**Example**
```
shader_set_ext(shd_shader, {
        uFloat: 1,
        uFloat3: [1, 2, 3],
        uTexture: sprite_get_texture(spr_texture, 0)
});
```

**Comment by DAndrewBox** [comment]
That could be a very good improvement to the code, you can create a PR to add this functionality to the shader_ext script!

Thank you Gizmo, your inputs are always very much appreciate

**Comment by Gizmo199** [comment]
No problem! Sure thing! I just happened to notice you have this function as well. It's such a more convenient way to use shaders. Haha. Great work also! This project has some really cool and useful things!

**Comment by DAndrewBox** [comment]
Added `u_texture` key to the params struct on version 1.1.0!
